/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlidaotao;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author os
 */
public class AdminFrame extends javax.swing.JFrame {
    DefaultTableModel tblModel;
    DefaultTableModel tblModelSV;
    
    List<GiangVien> gvList = new ArrayList<>();
    List<SinhVien> svList = new ArrayList<>();
    
    GVModify gVModify = new GVModify();
    SVModify sVModify = new SVModify();
    
    
    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        initComponents();
        
        tblModel = (DefaultTableModel) tblGiangVien.getModel();
        tblModelSV = (DefaultTableModel) tblSinhVien.getModel();
        
        showGV();
        showSV();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGiangVien = new javax.swing.JTable();
        btnAddGV = new javax.swing.JButton();
        btnReSetGV = new javax.swing.JButton();
        btnDeleteGV = new javax.swing.JButton();
        btnFindGV = new javax.swing.JButton();
        txtHoTenGV = new javax.swing.JTextField();
        txtDayGV = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMonthGV = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtYearGV = new javax.swing.JTextField();
        txtEmailGV = new javax.swing.JTextField();
        cbKhoaGV = new javax.swing.JComboBox<>();
        cbGioiTinhGV = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSinhVien = new javax.swing.JTable();
        btnAddSV = new javax.swing.JButton();
        btnResetSV = new javax.swing.JButton();
        btnDeleteSV = new javax.swing.JButton();
        btnFindSV = new javax.swing.JButton();
        txtHoTenSV = new javax.swing.JTextField();
        txtDaySV = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtMonthSV = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtYearSV = new javax.swing.JTextField();
        txtEmailSV = new javax.swing.JTextField();
        cbKhoaSV = new javax.swing.JComboBox<>();
        cbGioiTinhSV = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        txtNamNhapHoc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("QUẢN TRỊ HỆ THỐNG");

        jLabel2.setText("Họ Và Tên:*");

        jLabel3.setText("Giới Tính:*");

        jLabel4.setText("Ngày Sinh:*");

        jLabel5.setText("Email:*");

        jLabel6.setText("Khoa:*");

        tblGiangVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Họ Và Tên", "Giới Tính", "Ngày Sinh", "Email", "Khoa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblGiangVien);

        btnAddGV.setText("Thêm mới");
        btnAddGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGVActionPerformed(evt);
            }
        });

        btnReSetGV.setText("Nhập lại");
        btnReSetGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReSetGVActionPerformed(evt);
            }
        });

        btnDeleteGV.setText("Xóa bỏ");
        btnDeleteGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteGVActionPerformed(evt);
            }
        });

        btnFindGV.setText("Tìm kiếm");
        btnFindGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindGVActionPerformed(evt);
            }
        });

        jLabel7.setText("/");

        jLabel8.setText("/");

        cbKhoaGV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toán Học", "Hóa Học", "Vật Lí", "Sinh Học" }));

        cbGioiTinhGV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbKhoaGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtHoTenGV, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtDayGV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtMonthGV, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtYearGV, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtEmailGV))
                    .addComponent(cbGioiTinhGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnAddGV)
                .addGap(44, 44, 44)
                .addComponent(btnReSetGV)
                .addGap(64, 64, 64)
                .addComponent(btnDeleteGV)
                .addGap(60, 60, 60)
                .addComponent(btnFindGV)
                .addContainerGap(381, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHoTenGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbGioiTinhGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDayGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtMonthGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtYearGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEmailGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbKhoaGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddGV)
                    .addComponent(btnReSetGV)
                    .addComponent(btnDeleteGV)
                    .addComponent(btnFindGV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Giảng Viên", jPanel1);

        jLabel9.setText("Họ Và Tên:*");

        jLabel10.setText("Giới Tính:*");

        jLabel11.setText("Ngày Sinh:*");

        jLabel12.setText("Email:*");

        jLabel13.setText("Khoa:*");

        tblSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Họ Và Tên", "Giới Tính", "Ngày Sinh", "Email", "Khoa", "Năm nhập học"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblSinhVien);

        btnAddSV.setText("Thêm mới");
        btnAddSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSVActionPerformed(evt);
            }
        });

        btnResetSV.setText("Nhập lại");
        btnResetSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetSVActionPerformed(evt);
            }
        });

        btnDeleteSV.setText("Xóa bỏ");
        btnDeleteSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSVActionPerformed(evt);
            }
        });

        btnFindSV.setText("Tìm kiếm");
        btnFindSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindSVActionPerformed(evt);
            }
        });

        jLabel14.setText("/");

        jLabel15.setText("/");

        cbKhoaSV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toán Học", "Hóa Học", "Vật Lí", "Sinh Học" }));

        cbGioiTinhSV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        jLabel16.setText("Năm nhập học:*");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnAddSV)
                .addGap(44, 44, 44)
                .addComponent(btnResetSV)
                .addGap(64, 64, 64)
                .addComponent(btnDeleteSV)
                .addGap(60, 60, 60)
                .addComponent(btnFindSV)
                .addContainerGap(381, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbKhoaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtHoTenSV, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(txtDaySV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtMonthSV, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtYearSV, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtEmailSV))
                            .addComponent(cbGioiTinhSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(txtNamNhapHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtHoTenSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbGioiTinhSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtDaySV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtMonthSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtYearSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtEmailSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cbKhoaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtNamNhapHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddSV)
                    .addComponent(btnResetSV)
                    .addComponent(btnDeleteSV)
                    .addComponent(btnFindSV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 926, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Sinh Viên", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(341, 341, 341)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindGVActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog(this, "Nhập tên giảng viên cần tìm");
        if (input != null && input.length() > 0) {
            gvList = gVModify.findByTen(input);
            
            tblModel.setRowCount(0);
            
            for (GiangVien giangVien : gvList) {
                tblModel.addRow(new Object[]{tblModel.getRowCount() + 1, giangVien.getHoTen(), giangVien.getGioiTinh(), giangVien.getNgaySinh(), giangVien.getEmail(), giangVien.getKhoa()});
            }
        }else{
            showGV();
        }
    }//GEN-LAST:event_btnFindGVActionPerformed

    private void btnAddGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGVActionPerformed
        // TODO add your handling code here:
        String hoTen = txtHoTenGV.getText().trim();
        String gioiTinh = cbGioiTinhGV.getSelectedItem().toString();
        String ngaySinh = txtDayGV.getText().trim() + "/" + txtMonthGV.getText().trim() + "/" + txtYearGV.getText().trim();
        String email = txtEmailGV.getText().trim();
        String khoa = cbKhoaGV.getSelectedItem().toString();
        
        GiangVien gv = new GiangVien(hoTen, gioiTinh, ngaySinh, email, khoa);
        
        gVModify.insert(gv);
        
        showGV();
    }//GEN-LAST:event_btnAddGVActionPerformed

    private void btnReSetGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReSetGVActionPerformed
        // TODO add your handling code here:
        txtHoTenGV.setText("");
        cbGioiTinhGV.setSelectedIndex(0);
        txtDayGV.setText("");
        txtMonthGV.setText("");
        txtYearGV.setText("");
        txtEmailGV.setText("");
        cbKhoaGV.setSelectedIndex(0);
    }//GEN-LAST:event_btnReSetGVActionPerformed

    private void btnDeleteGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteGVActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tblGiangVien.getSelectedRow();
        if (selectedIndex >= 0) {
            GiangVien gv = gvList.get(selectedIndex);
            
            int option = JOptionPane.showConfirmDialog(this, "Bạn muốn xóa?");
            System.out.println(option);
            if (option == 0) {
                gVModify.delete(gv);
            }
        }
        showGV();
    }//GEN-LAST:event_btnDeleteGVActionPerformed

    private void btnAddSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSVActionPerformed
        // TODO add your handling code here:
        String hoTen = txtHoTenSV.getText().trim();
        String gioiTinh = cbGioiTinhSV.getSelectedItem().toString();
        String ngaySinh = txtDaySV.getText().trim() + "/" + txtMonthSV.getText().trim() + "/" + txtYearSV.getText().trim();
        String email = txtEmailSV.getText().trim();
        String khoa = cbKhoaSV.getSelectedItem().toString();
        String namNhapHoc = txtNamNhapHoc.getText().trim();
        
        SinhVien sv = new SinhVien(hoTen, gioiTinh, ngaySinh, email, khoa, namNhapHoc);
        
        sVModify.insert(sv);
        
        showSV();
    }//GEN-LAST:event_btnAddSVActionPerformed

    private void btnResetSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetSVActionPerformed
        // TODO add your handling code here:
        txtHoTenSV.setText("");
        cbGioiTinhSV.setSelectedIndex(0);
        txtDaySV.setText("");
        txtMonthSV.setText("");
        txtYearSV.setText("");
        txtEmailSV.setText("");
        cbKhoaSV.setSelectedIndex(0);
        txtNamNhapHoc.setText("");
    }//GEN-LAST:event_btnResetSVActionPerformed

    private void btnDeleteSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSVActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tblSinhVien.getSelectedRow();
        if (selectedIndex >= 0) {
            SinhVien sv = svList.get(selectedIndex);
            
            int option = JOptionPane.showConfirmDialog(this, "Bạn muốn xóa?");
            System.out.println(option);
            if (option == 0) {
                sVModify.delete(sv);
            }
        }
        showSV();
    }//GEN-LAST:event_btnDeleteSVActionPerformed

    private void btnFindSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindSVActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog(this, "Nhập tên sinh viên cần tìm");
        if (input != null && input.length() > 0) {
            svList = sVModify.findByTen(input);
            
            tblModelSV.setRowCount(0);
            
            for (SinhVien sinhVien : svList) {
                tblModelSV.addRow(new Object[]{tblModelSV.getRowCount() + 1, sinhVien.getHoTen(), sinhVien.getGioiTinh(), sinhVien.getNgaySinh(), sinhVien.getEmail(), sinhVien.getKhoa(), sinhVien.getNamNhapHoc()});
            }
        }else{
            showSV();
        }
    }//GEN-LAST:event_btnFindSVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }
    
    private void showGV(){
        gvList = gVModify.findAll();
        
        tblModel.setRowCount(0);
        
        for (GiangVien giangVien : gvList) {
          tblModel.addRow(new Object[]{tblModel.getRowCount() + 1, giangVien.getHoTen(), giangVien.getGioiTinh(), giangVien.getNgaySinh(), giangVien.getEmail(), giangVien.getKhoa()});
        }
    }

    private void showSV(){
        svList = sVModify.findAll();
        
        tblModelSV.setRowCount(0);
        
        for (SinhVien sinhVien : svList) {
          tblModelSV.addRow(new Object[]{tblModelSV.getRowCount() + 1, sinhVien.getHoTen(), sinhVien.getGioiTinh(), sinhVien.getNgaySinh(), sinhVien.getEmail(), sinhVien.getKhoa(), sinhVien.getNamNhapHoc()});
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddGV;
    private javax.swing.JButton btnAddSV;
    private javax.swing.JButton btnDeleteGV;
    private javax.swing.JButton btnDeleteSV;
    private javax.swing.JButton btnFindGV;
    private javax.swing.JButton btnFindSV;
    private javax.swing.JButton btnReSetGV;
    private javax.swing.JButton btnResetSV;
    private javax.swing.JComboBox<String> cbGioiTinhGV;
    private javax.swing.JComboBox<String> cbGioiTinhSV;
    private javax.swing.JComboBox<String> cbKhoaGV;
    private javax.swing.JComboBox<String> cbKhoaSV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblGiangVien;
    private javax.swing.JTable tblSinhVien;
    private javax.swing.JTextField txtDayGV;
    private javax.swing.JTextField txtDaySV;
    private javax.swing.JTextField txtEmailGV;
    private javax.swing.JTextField txtEmailSV;
    private javax.swing.JTextField txtHoTenGV;
    private javax.swing.JTextField txtHoTenSV;
    private javax.swing.JTextField txtMonthGV;
    private javax.swing.JTextField txtMonthSV;
    private javax.swing.JTextField txtNamNhapHoc;
    private javax.swing.JTextField txtYearGV;
    private javax.swing.JTextField txtYearSV;
    // End of variables declaration//GEN-END:variables
}
